### ISSUE TITLE
Support for 'hcledit fmt'

### ISSUE THREAD

**Issue by tristanmorgan** [minamijoyo/hcledit#13]
Similar to how JQ works having '*' or some alternative (maybe "--all"), to let you output the whole file with all of its resources and blocks.
The uses could be to check if a file contains no errors, or to use as a formatter for hcl config files.

**Comment by minamijoyo** [comment]
@tristanmorgan If you intend to use it only for syntax check or format, why don't you add `hcledit fmt`? I feel using hcledit block `*` for it isn't intuitive.

**Comment by tristanmorgan** [comment]
Hi @minamijoyo , Yes 'fmt' sounds even better.

**Comment by minamijoyo** [comment]
It's easy to support it because we already have building blocks internally, and only we need is combining them and adding `fmt` command.

**Comment by minamijoyo** [comment]
@tristanmorgan Added fmt in v0.1.2
