### ISSUE TITLE
Add support for using this in another Go application

### ISSUE THREAD

**Issue by Gaardsholt** [minamijoyo/hcledit#29]
I would be awesome if you could make it available through Go.
So I could just import this library in my own application and use this great magic !

**Comment by minamijoyo** [comment]
Hi @Gaardsholt, I think it's already possible. The core logics are in the `editor` package. Why don't you give it a try? Note that I cannot promise the stability for any public APIs.

**Comment by minamijoyo** [comment]
I'm going to close this because of no reply, but feel free reopen if you have any questions.
