### ISSUE TITLE
Can I Set the negative value of a number?

### ISSUE THREAD

**Issue by tkyggit** [minamijoyo/hcledit#46]
If you try to set a negative value for a number, it will be recognized as a flag. Is there any way to escape it?

**Comment by minamijoyo** [comment]
@tkyggit Thank you for reporting this. I didn't know this strange behavior.

The hcledit uses a spf13/cobra as a CLI framework and I found an upstream issue: https://github.com/spf13/cobra/issues/124

**Comment by minamijoyo** [comment]
@tkyggit Looks adding `--` before key works.

```
$ echo 'foo = 1' | hcledit attribute set -- foo -1
foo = -1
```
