### ISSUE TITLE
[Question] - How to pass and parse input to command

### ISSUE THREAD

**Issue by aleqsss** [minamijoyo/hcledit#70]
Hi @minamijoyo,

Great work on this CLI tool for editing HCL2 files! 👍

I myself am also doing some work using the **hclwrite**  package. However, I'm completely new to Go and I'm nowhere near your level looking at your code.

What I struggle to do/achieve, is something similar to your example:
```
$ cat tmp/block.hcl | hcledit block append resource.foo.bar block1.label1 --newline
resource "foo" "bar" {
  attr1 = "val1"

  block1 "label1" {
  }
}

resource "foo" "baz" {
  attr1 = "val2"
}
```

Where I can see that it's possible to specify nested blocks, to be able to append to their bodies.

I'm creating a "console" application, in which I need to be able to add blocks/set attributes (amongst other operations from the **hclwrite** package) within specific bodies (blocks). Do you have any guidance for me how to do this, more than looking at your code (which I've done but fail to understand exactly what I'd need to implement).

For example, I have the following function:
```
func AddHCL2Block(hcl2Configuration []byte, typeName string, labels []string) []byte {
	parsedConfig, diags := hclwrite.ParseConfig(hcl2Configuration, "HCL2configuration", hcl.Pos{Line: 1, Column: 1})
	if diags.HasErrors() {
		log.Fatalf("Errors: %s", diags)
	}

	parsedConfig.Body().AppendNewBlock(typeName, labels)

	return parsedConfig.Bytes()
}
```

This appends the block to the root body, but I'd like to add a parameter to the function which allows me to specify which body (block) I'd like to append the new block to, just as you can, by passing a properly formatted string to your `hcledit block append` command.

Your input would be very much appreciated, since I'm quite far into a project and have been struggling with this all along. Unfortunately I've not been able to solve this on my own, I've been struggling with this for weeks, I don't even now where to start. Now when I discovered your tool, I got my hopes up since there's someone that've actually done what I'm trying to do, so it for sure can't be impossible.

Crossing my fingers here. 🤞

Best regards

**Comment by minamijoyo** [comment]
Developing an application like hcledit, it’s inevitable to understand the HCL specification and implementation. And since the hcl library is implemented in Go, of course, you also need to understand programming Go. Learn Go and the HCL itself first. Then you will know how to implement it.
https://go.dev/
https://github.com/hashicorp/hcl
