### ISSUE TITLE
Publish windows artifact

### ISSUE THREAD

**Issue by mttwise** [minamijoyo/hcledit#72]
Is it possible to publish a windows exe as part of the release artifacts?

I am having issues building the GO lib as my corporate laptop blocks the GO package manager downloads

**Comment by minamijoyo** [comment]
Hi @mttwise, Thank you for your proposal.

As I don't have a Windows development environment, it would be difficult to fix the problem on my side if something needs to be fixed on Windows. I expect the community, including you, to report and resolve issues.

Given the above, have you already confirmed that hcledit works on Windows? In other words, is the problem only for the release artifacts?

**Comment by mttwise** [comment]
Hi @minamijoyo, thanks for the quick response.

I was able to build the windows artifact by using an EC2 instance with full internet access and doing the following:

Start the golang docker:
```
kubectl run -it --image golang:1.18.3-alpine3.16 golang
```

Install dependencies and build windows package:
```
apk  add --no-cache make bash git

mkdir /work
cd /work
git clone https://github.com/minamijoyo/hcledit
cd hcledit

go mod download

export GOARCH=amd64
export GOOS=windows

make build
``` 

I copied out the artifact to a windows machine and confirmed I was able to correctly edit hcl files.

I was hoping to have it included starting in the release to make future maintenance easier. Having hcledit in chocolatey (windows equivalent of homebrew) would be ideal. https://docs.chocolatey.org/en-us/features/create-packages

**Comment by minamijoyo** [comment]
Thanks for the test. I will try to add Windows to the build target starting with the next release.

At the time of writing, I don’t have a plan to support the chocolatey, but anyway, I will at least upload the artifact to GitHub Release.

**Comment by minamijoyo** [comment]
@mttwise, I’ve cut a pre-release. Could you check this?
https://github.com/minamijoyo/hcledit/releases/tag/v0.2.7-beta1

**Comment by mttwise** [comment]
@minamijoyo Tested an it works!

**Comment by minamijoyo** [comment]
@mttwise v0.2.7 has been released 🚀
